# yaml 配置
# 官方文档：https://docs.docker.com/compose/compose-file/
version: "3.7"
services:
  app:
    container_name: go-app
    build: .
    links:
      - "db:mysql"
      - redis
    ports:
      - "8080:8080"
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]   # 用于健康检查的指令
      interval: 1m30s   # 间隔时间
      timeout: 10s  # 超时时间
      retries: 3    # 重试次数
      start_period: 40s # 启动多久后开始检查

  db:
    container_name: mysql57
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "snake"
      MYSQL_PASSWORD: "123456"
      TZ: Asia/Shanghai
    # 解决外部无法访问 for mysql8
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    stdin_open: true
    tty: true
    # 修复问题 mbind: Operation not permitted
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./db.sql:/data/application/init.sql
      - ./build/docker/mysql/my.cnf:/etc/mysql/my.cnf
      - mysql-data:/var/lib/mysql
    networks:
      - default

  # web 数据库管理工具，tips: host使用 db:3306
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    links:
      - "db:mysql"
    ports:
      - 8036:8080

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - default
    volumes:
      - redis_data:/var/lib/redis

  nginx:
    container_name: nginx
    image: nginx:1.17.10-alpine
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./conf/nginx_api.conf:/etc/nginx/conf.d/default.conf
    command: nginx -g 'daemon off';

networks:
  default:
    driver: "bridge"

volumes:
  mysql-data:
  redis_data:
